---

_You are currently looking at **version 1.0** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

# Pandas

Pandas deals with the following three data structures âˆ’

1] Series <br>
      Series is a one-dimensional array like structure with homogeneous data. 

      Key Points
        Homogeneous data
        Size Immutable
        Values of Data Mutable

2] DataFrame <br>
      DataFrame is a two-dimensional array with heterogeneous data.

      Key Points
        Heterogeneous data
        Size Mutable
        Data Mutable

3] Panel <br>
Panel is a three-dimensional data structure with heterogeneous data. 

      Key Points
        Heterogeneous data
        Size Mutable
        Data Mutable


These data structures are built on top of Numpy array, which means they are fast.

The best way to think of these data structures is that the higher dimensional data structure is a container of its lower dimensional data structure. For example, DataFrame is a container of Series, Panel is a container of DataFrame.

# The Series

The series is one of the core data structures in pandas. You think of it a cross between a list and a dictionary. The items are all stored in an order and there's labels with which you can retrieve them. An easy way to visualize this is two columns of data. The first is the special index, a lot like the dictionary keys. While the second is your actual data.

It's important to note that the data column has a label of its own and can be retrieved using the .name attribute.

<br>

In [1]:
import pandas as pd

# A basic series, which can be created is an Empty Series.

s = pd.Series()
s
# pd.Series?

Series([], dtype: float64)

You can create a series by passing in a list of values. When you do this, Pandas automatically assigns an index starting with zero and sets the name of the series to None.

The data can be anything, that's array-like, like a list.

In [2]:
animals = ['Tiger', 'Bear', 'Moose']
pd.Series(animals)

0    Tiger
1     Bear
2    Moose
dtype: object

In [3]:
import pandas as pd
import numpy as np
data = np.array(['a','b','c','d'])
print(data)
s = pd.Series(data)
print(s)

['a' 'b' 'c' 'd']
0    a
1    b
2    c
3    d
dtype: object

In [4]:
numbers = [1, 2, 3]
pd.Series(numbers)

0    1
1    2
2    3
dtype: int64

In [5]:
animals = ['Tiger', 'Bear', None, 1, 2]
a = pd.Series(animals)
print(a)
a[0]

0    Tiger
1     Bear
2     None
3        1
4        2
dtype: object

'Tiger'

If we create a list of strings and we have one element, a None type, pandas inserts it as a None and uses the type object for the underlying array. 
<br>
If we create a list of numbers, integers or floats, and put in the None type, pandas automatically converts this to a special floating point value designated as NAN, which stands for not a number.

In [6]:
numbers = [1, 2, None]
pd.Series(numbers)

0    1.0
1    2.0
2    NaN
dtype: float64

NAN is not none and when we try the equality test, it's false.

In [7]:
import numpy as np
np.nan == None

False

It turns out that you actually can't do an equality test of NAN to itself. When you do, the answer is always false. You need to use special functions to test for the presence of not a number, such as the Numpy library is NAN.

<br>
When you see NAN, it's meaning is similar to none, but it's a numeric value and it's treated differently for efficiency reasons.

In [8]:
np.nan == np.nan

False

In [9]:
np.isnan(np.nan)

True

Once the series has been created, we can get the index object using the index attribute.

In [10]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports)
s

Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
dtype: object

In [11]:
s.index

Index(['Archery', 'Golf', 'Sumo', 'Taekwondo'], dtype='object')


You could also separate your index creation from the data by passing in the index as a list explicitly to the series.

In [12]:
s = pd.Series(['Tiger', 'Bear', 'Moose'], index=['India', 'America', 'Canada'])
s
s.index

Index(['India', 'America', 'Canada'], dtype='object')

So what happens if your list of values in the index object are not aligned with the keys in your dictionary for creating the series? Well, pandas overrides the automatic creation to favor only and all of the indices values that you provided. So it will ignore it from your dictionary, all keys, which are not in your index, and pandas will add non type or NAN values for any index value you provide, which is not in your dictionary key list.

In [13]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports, index=['Golf', 'Sumo', 'Hockey'])
s

Golf      Scotland
Sumo         Japan
Hockey         NaN
dtype: object

# Querying a Series

As we saw, if you don't give an index to the series, the position and the label are effectively the same values.

In [14]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports)
print("s is: \n %s" % s)

print('----------------')

print('s indexing s[0] is %s' % s[0])

print('----------------')

for k,v in s.items():
  print(k,v)

s is:
 Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
dtype: object
----------------
s indexing s[0] is Bhutan
----------------
Archery Bhutan
Golf Scotland
Sumo Japan
Taekwondo South Korea

To query by numeric location, starting at zero, use the iloc attribute

In [15]:
print('s iloc[3] %s' % s.iloc[3])

print('-------------------')

print('s iloc[:2]:\n %s' % s.iloc[:2])

s iloc[3] South Korea
-------------------
s iloc[:2]:
 Archery      Bhutan
Golf       Scotland
dtype: object

To query by the index label, you can use the loc attribute.

<br>

Keep in mind that iloc and loc are not methods, they are attributes. So you don't use parentheses to query them, but square brackets instead, we'll call the indexing operator.

In [16]:
s.loc['Golf']

'Scotland'

In [17]:
s[3]

'South Korea'

In [18]:
s['Golf']

'Scotland'

In [19]:
sports = {99: 'Bhutan',
          100: 'Scotland',
          101: 'Japan',
          102: 'South Korea'}
s = pd.Series(sports)
s

99          Bhutan
100       Scotland
101          Japan
102    South Korea
dtype: object

In [20]:
s[0] #This won't call s.iloc[0] as one might expect, it generates an error instead

KeyError: ignored

In [21]:
s[99]

'Bhutan'

In [22]:
print(s[99:101])

Series([], dtype: object)

So what happens if your index is a list of integers? This is a bit complicated, and Pandas can't determine automatically whether you're intending to query by index position or index label. So you need to be careful when using the indexing operator on the series itself. And the safer option is to be more explicit and use the iloc or loc attributes directly.

In [23]:
s = pd.Series([100.00, 120.00, 101.00, 3.00])
s

0    100.0
1    120.0
2    101.0
3      3.0
dtype: float64

In [24]:
s[0]

100.0

In [25]:
s[1]

120.0

In [26]:
total = 0
for item in s:
    total+=item
print(total)

324.0

In [27]:
import numpy as np

total = np.sum(s)
print(total)

324.0

In [28]:
#this creates a big series of random numbers
s = pd.Series(np.random.randint(0,1000,10000))
s.head()

0    114
1      4
2    616
3    777
4    603
dtype: int64

In [0]:
len(s)

Magic functions begin with a percentage sign. If we type this sign and then hit the Tab key, we can see a list of the available magic functions. You could write your own magic functions too.

We're actually going to use what's called a cellular magic function. These start with two percentage signs and modify a raptor code in the current Jupyter cell. 

The function we're going to use is called timeit. This function will run our code a few times to determine, on average, how long it takes.

In [29]:
%%timeit -n 10000
summary = 0
for item in s:
    summary+=item

10000 loops, best of 3: 1.13 ms per loop

This is a pretty shocking difference in the speed and demonstrates why data scientists need to be aware of **parallel computing features** and start thinking in functional programming terms.

In [30]:
%%timeit -n 10000
summary = np.sum(s)

10000 loops, best of 3: 78.6 Âµs per loop

Related feature in Pandas and NumPy is called broadcasting. With broadcasting, you can apply an operation to every value in the series, changing the series.

For instance, if we wanted to increase every random variable by 2, we could do so quickly using the += operator directly on the series object

In [31]:
s+=2 #adds two to each item in s using broadcasting
s.head()

0    116
1      6
2    618
3    779
4    605
dtype: int64

The procedural way of doing this would be to iterate through all of the items in the series and increase the values directly. A quick aside here. Pandas does support iterating through a series much like a dictionary, allowing you to unpack values easily. But if you find yourself iterating through a series, you should question whether you're doing things in the best possible way.

In [0]:
for label, value in s.iteritems():
    s.set_value(label, value+2)
s.head()

In [0]:
%%timeit -n 10
s = pd.Series(np.random.randint(0,1000,10000))
for label, value in s.iteritems():
    s.loc[label]= value+2

In [0]:
%%timeit -n 10
s = pd.Series(np.random.randint(0,1000,10000))
s+=2

The typical mathematical operations you would expect are vectorized, and the NumPy documentation outlines what it takes to create vectorized functions of your own. One last note on using the indexing operators to access series data. The .loc attribute lets you not only modify data in place, but also add new data as well. If the value you pass in as the index doesn't exist, then a new entry is added. And keep in mind, indices can have mixed types. While it's important to be aware of the typing going on underneath, Pandas will automatically change the underlying NumPy types as appropriate.

In [0]:
s = pd.Series([1, 2, 3])
s.loc['Animal'] = 'Bears'
s

In [0]:
original_sports = pd.Series({'Archery': 'Bhutan',
                             'Golf': 'Scotland',
                             'Sumo': 'Japan',
                             'Taekwondo': 'South Korea'})
cricket_loving_countries = pd.Series(['Australia',
                                      'Barbados',
                                      'Pakistan',
                                      'England'], 
                                   index=['Cricket',
                                          'Cricket',
                                          'Cricket',
                                          'Cricket'])
all_countries = original_sports.append(cricket_loving_countries)

In [0]:
original_sports

In [0]:
cricket_loving_countries

In [0]:
all_countries

In [0]:
all_countries.loc['Cricket']

In [0]:
s = {1: 'hi', 1: 'hello'}
s

# The DataFrame Data Structure

The DataFrame data structure is the heart of the Panda's library. 

It's a primary object that we work on for data analysis and cleaning tasks.

<br>

The DataFrame is conceptually a two-dimensional series object, where there's an index and multiple columns of content, with each column having a label. In fact, the distinction between a column and a row is really only a conceptual distinction. And you can think of the DataFrame itself as simply a two-axes labeled array.

In [0]:
import pandas as pd
purchase_1 = pd.Series({'Name': 'Chris',                      # Each key will become a label in DF.
                        'Item Purchased': 'Dog Food',
                        'Cost': 22.50})
purchase_2 = pd.Series({'Name': 'Kevyn',
                        'Item Purchased': 'Kitty Litter',
                        'Cost': 2.50})
purchase_3 = pd.Series({'Name': 'Vinod',
                        'Item Purchased': 'Bird Seed',
                        'Cost': 5.00,
                        'LOcation': 'India'})                 # If a label is unique and not present in other places, it will add NaN to those locations.
df = pd.DataFrame([purchase_1, purchase_2, purchase_3], index=['Store 1', 'Store 1', 'Store 2'])
df.head()

In [0]:
df.loc['Store 2']

In [0]:
type(df.loc['Store 2'])

In [0]:
df.loc['Store 1']

In [0]:
df.loc['Store 1', 'Cost']

What if we just wanted to do column selection and just get a list of all of the costs? Well, there's a couple of options. First, you can get a transpose of the DataFrame, using the capital T attribute, which swaps all of the columns and rows. This essentially turns your column names into indices. And we can then use the .lock method. This works, but it's pretty ugly.

Since iloc and loc are used for row selection, the Panda's developers reserved indexing operator directly on the DataFrame for column selection. In a Panda's DataFrame, columns always have a name. So this selection is always label based, not as confusing as it was when using the square bracket operator on the series objects.

In [0]:
df.T

In [0]:
df.T.loc['Cost']

In [0]:
df['Cost']

In [0]:
df.loc['Store 1']['Cost']

In particular, **chaining** tends to cause Pandas to return a copy of the DataFrame instead of a view on the DataFrame. For selecting a data, this is not a big deal, though it might be slower than necessary. If you are changing data though, this is an important distinction and can be a source of error.

In [0]:
df.loc[:,['Name', 'Cost']]

t's easy to delete data in series and DataFrames, and we can use the drop function to do so. This function takes a single parameter, which is the index or roll label, to drop. 

<br>

This is another tricky place for new users to pad this. The drop function doesn't change the DataFrame by default. And instead, returns to you a copy of the DataFrame with the given rows removed. We can see that our original DataFrame is still intact

In [0]:
df.drop('Store 1')

In [0]:
df

In [0]:
copy_df = df.copy()
copy_df = copy_df.drop('Store 1')
copy_df

In [0]:
copy_df.drop?

In [0]:
del copy_df['Name']
copy_df

In [0]:
df['Location'] = None
df

# Dataframe Indexing and Loading

As you've seen, the Panda's toolkit tries to give you views on a DataFrame. This is much faster than copying data and much more memory efficient too.

<br>

But it does mean that if you're manipulating the data you have to be aware that any changes to the DataFrame you're working on may have an impact on the base data frame you used originally.

<br>

Here's an example using our same purchasing DataFrame from earlier. We can create a series based on just the cost category using the square brackets. Then we can increase the cost in this series using broadcasting. Now if we look at our original DataFrame, we see those costs have risen as well. This is an important consideration to watch out for. If you want to explicitly use a copy, then you should consider calling the copy method on the DataFrame for it first.

In [0]:
costs = df['Cost']
costs

In [0]:
costs+=2
costs

In [0]:
df

In [0]:
!cat olympics.csv

In [0]:
df = pd.read_csv('olympics.csv')
df.head()

In [0]:
df = pd.read_csv('olympics.csv', index_col = 0, skiprows=1)
df.head()

In [0]:
df.columns

In [0]:
for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold' + col[4:]}, inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver' + col[4:]}, inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze' + col[4:]}, inplace=True)
    if col[:1]=='â„–':
        df.rename(columns={col:'#' + col[1:]}, inplace=True) 

df.head()

# Querying a DataFrame

In [0]:
df['Gold'] > 0

In [0]:
only_gold = df.where(df['Gold'] > 0)
only_gold.head()

In [0]:
only_gold['Gold'].count()

In [0]:
df['Gold'].count()

In [0]:
only_gold = only_gold.dropna()
only_gold.head()

In [0]:
only_gold = df[df['Gold'] > 0]
only_gold.head()

In [0]:
len(df[(df['Gold'] > 0) | (df['Gold.1'] > 0)])

In [0]:
df[(df['Gold.1'] > 0) & (df['Gold'] == 0)]

# Indexing Dataframes

The index is essentially a row level label, and we know that rows correspond to axis zero

In [0]:
df.head()

In [0]:
df['country'] = df.index
df = df.set_index('Gold')
df.head()

In [0]:
df = df.reset_index()
df.head()

In [0]:
df = pd.read_csv('census.csv')
df.head()

In [0]:
df['SUMLEV'].unique()

In [0]:
df=df[df['SUMLEV'] == 50]
df.head()

In [0]:
columns_to_keep = ['STNAME',
                   'CTYNAME',
                   'BIRTHS2010',
                   'BIRTHS2011',
                   'BIRTHS2012',
                   'BIRTHS2013',
                   'BIRTHS2014',
                   'BIRTHS2015',
                   'POPESTIMATE2010',
                   'POPESTIMATE2011',
                   'POPESTIMATE2012',
                   'POPESTIMATE2013',
                   'POPESTIMATE2014',
                   'POPESTIMATE2015']
df = df[columns_to_keep]
df.head()

In [0]:
df = df.set_index(['STNAME', 'CTYNAME'])
df.head()

In [0]:
df.loc['Michigan', 'Washtenaw County']

In [0]:
df.loc[ [('Michigan', 'Washtenaw County'),
         ('Michigan', 'Wayne County')] ]

# Missing values

In [0]:
df = pd.read_csv('log.csv')
df

In [0]:
df.fillna?

In [0]:
df = df.set_index('time')
df = df.sort_index()
df

In [0]:
df = df.reset_index()
df = df.set_index(['time', 'user'])
df

In [0]:
df = df.fillna(method='ffill')
df.head()